version: 0.0
os: linux
files:
  - source: /
    destination: /triangles
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3000
      runas: root